# -*- coding: utf-8 -*-

# Author: Florian Le Roux

import resources
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class mainGUI(QtCore.QObject):
    
    def __init__(self, OneGUI):
        
        """Initialise mainwindow."""
        super().__init__()
        self.setupUi(OneGUI)
        
    def setupUi(self, MainWindow):
        
        MainWindow.setWindowIcon(QtGui.QIcon(":/OneIcon.png"));
        MainWindow.setObjectName("WLRGUI")
        MainWindow.resize(1900, 1100)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 1020))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 1020))
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("border-color: rgb(206, 206, 206);")    
        
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName('statusBar')
        MainWindow.setStatusBar(self.statusBar)  
        
        self.statusButton = QtWidgets.QLabel(self.centralWidget)
        self.statusButton.setMaximumSize(QtCore.QSize(60, 60))
        self.statusButton.setGeometry(QtCore.QRect(475, 0, 60,60))
        self.statusButton.setText("")
        self.statusButton.setPixmap(QtGui.QPixmap(":/RedButton.png"))
        self.statusButton.setScaledContents(True)
        self.statusButton.setObjectName("statusButton") 
        
        self.statusSampleStageButton = QtWidgets.QLabel(self.centralWidget)
        self.statusSampleStageButton.setMaximumSize(QtCore.QSize(60, 60))
        self.statusSampleStageButton.setGeometry(QtCore.QRect(475, 450, 60,60))
        self.statusSampleStageButton.setText("")
        self.statusSampleStageButton.setPixmap(QtGui.QPixmap(":/RedButton.png"))
        self.statusSampleStageButton.setScaledContents(True)
        self.statusSampleStageButton.setObjectName("statusSampleStageButton") 
        
        
        self.logFrame = QtWidgets.QFrame(self.centralWidget)
        self.logFrame.setGeometry(QtCore.QRect(580, 505, 500, 485))      
        
        self.logFrame.setAutoFillBackground(True)
        self.logFrame.setStyleSheet("border-color: rgb(142, 231, 255);")
        self.logFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.logFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logFrame.setLineWidth(4)
        self.logFrame.setObjectName("LogFrame")
        
        self.Log = QtWidgets.QTextEdit(self.logFrame)
        self.Log.setGeometry(QtCore.QRect(7, 7, 486, 471))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Log.setFont(font)
        self.Log.setFrameStyle(0)
        self.Log.setReadOnly(True)
        self.Log.setObjectName("Log")
        
        #Rotating Stage Widget
        
        self.rotatinggridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.rotatinggridLayoutWidget.setGeometry(QtCore.QRect(30, 80, 540, 160))
        self.rotatinggridLayoutWidget.setObjectName("rotatinggridLayoutWidget")
        self.rotatinggridLayout = QtWidgets.QGridLayout(self.rotatinggridLayoutWidget)
        self.rotatinggridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.rotatinggridLayout.setContentsMargins(11, 11, 11, 11)
        self.rotatinggridLayout.setSpacing(6)
        self.rotatinggridLayout.setObjectName("rotatinggridLayout")
        
        self.topArmButton = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        self.topArmButton.setMaximumSize(QtCore.QSize(40, 40))
        self.topArmButton.setText("")
        self.topArmButton.setPixmap(QtGui.QPixmap(":/RedButton.png"))
        self.topArmButton.setScaledContents(True)
        self.topArmButton.setObjectName("topArmButton")
        self.rotatinggridLayout.addWidget(self.topArmButton, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        
        self.btmAxisLabelTxt = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        
        self.btmAxisLabelTxt.setFont(font)
        self.btmAxisLabelTxt.setObjectName("label_2")
        self.rotatinggridLayout.addWidget(self.btmAxisLabelTxt, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.crtStepLabelTxt = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        
        self.crtStepLabelTxt.setFont(font)
        self.crtStepLabelTxt.setObjectName("label_5")
        
        self.rotatinggridLayout.addWidget(self.crtStepLabelTxt, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        
        self.emptyRotatingLabel = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        self.emptyRotatingLabel.setText("")
        self.emptyRotatingLabel.setObjectName("label_3")
        self.rotatinggridLayout.addWidget(self.emptyRotatingLabel, 0, 0, 1, 1)
        self.topAxisLabelTxt = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.topAxisLabelTxt.setFont(font)
        self.topAxisLabelTxt.setObjectName("label")
        self.rotatinggridLayout.addWidget(self.topAxisLabelTxt, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        
        self.stepLCDTop = QtWidgets.QLCDNumber(self.rotatinggridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(6)
        self.stepLCDTop.setFont(font)
        self.stepLCDTop.digitCount = 7
        self.stepLCDTop.setStyleSheet("\n"
"background-color: rgb(226, 239, 255);")
        self.stepLCDTop.setFrameShape(QtWidgets.QFrame.Box)
        self.stepLCDTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stepLCDTop.setSmallDecimalPoint(False)
        self.stepLCDTop.setNumDigits(8)
        self.stepLCDTop.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.stepLCDTop.setObjectName("lcdNumber")
        self.rotatinggridLayout.addWidget(self.stepLCDTop, 1, 2, 1, 1)
        self.statsLabelTxt = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.statsLabelTxt.setFont(font)
        self.statsLabelTxt.setObjectName("label_4")
        self.rotatinggridLayout.addWidget(self.statsLabelTxt, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.crtAngleLabelTxt = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.crtAngleLabelTxt.setFont(font)
        self.crtAngleLabelTxt.setObjectName("label_6")
        self.rotatinggridLayout.addWidget(self.crtAngleLabelTxt, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.stepLCDBt = QtWidgets.QLCDNumber(self.rotatinggridLayoutWidget)
        self.stepLCDBt.setStyleSheet("\n"
"background-color: rgb(226, 239, 255);")
        self.stepLCDBt.setObjectName("stepLCDBt")
        self.stepLCDBt.setNumDigits(8)
        self.rotatinggridLayout.addWidget(self.stepLCDBt, 2, 2, 1, 1)
        self.angleLCDTop = QtWidgets.QLCDNumber(self.rotatinggridLayoutWidget)
        self.angleLCDTop.setStyleSheet("\n"
"background-color: rgb(226, 239, 255);")
        self.angleLCDTop.setObjectName("angleLCDTop")
        self.rotatinggridLayout.addWidget(self.angleLCDTop, 1, 3, 1, 1)
        self.angleLCDBt = QtWidgets.QLCDNumber(self.rotatinggridLayoutWidget)
        self.angleLCDBt.setStyleSheet("background-color: rgb(226, 239, 255);")
        self.angleLCDBt.setObjectName("angleLCDTop")
        self.rotatinggridLayout.addWidget(self.angleLCDBt, 2, 3, 1, 1)
        self.btArmButton = QtWidgets.QLabel(self.rotatinggridLayoutWidget)
        self.btArmButton.setMaximumSize(QtCore.QSize(40, 40))
        self.btArmButton.setText("")
        self.btArmButton.setPixmap(QtGui.QPixmap(":/RedButton.png"))
        self.btArmButton.setScaledContents(True)
        self.btArmButton.setObjectName("btArmButton")
        self.rotatinggridLayout.addWidget(self.btArmButton, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.rotatinggridLayout.setRowMinimumHeight(1, 50)
        self.rotatinggridLayout.setRowMinimumHeight(2, 50)
        self.rotatinggridLayout.setRowStretch(0, 1)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        
        self.OperationMdLabelTxt = QtWidgets.QLabel(self.centralWidget)
        self.OperationMdLabelTxt.setGeometry(QtCore.QRect(200, 255, 230, 30))
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        
        self.OperationMdLabelTxt.setFont(font)
        self.OperationMdLabelTxt.setObjectName("OperationMode")
        
        self.verticalLayoutRotatingStage = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutRotatingStage.setGeometry(QtCore.QRect(33, 270, 520, 200))
        self.verticalLayoutRotatingStage.setObjectName("verticalLayoutWidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutRotatingStage)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("horizontalLayout")
        
        self.InitCheckBtn = QtWidgets.QPushButton(self.verticalLayoutRotatingStage)
        self.InitCheckBtn.setObjectName("InitCheckBtn")
        self.verticalLayout.addWidget(self.InitCheckBtn)
        
        self.freeMoveBtn = QtWidgets.QPushButton(self.verticalLayoutRotatingStage)
        self.freeMoveBtn.setObjectName("freeMoveBtn")
        self.verticalLayout.addWidget(self.freeMoveBtn)
        
        self.reflectionBtn = QtWidgets.QPushButton(self.verticalLayoutRotatingStage)
        self.reflectionBtn.setObjectName("reflectionBtn")
        self.verticalLayout.addWidget(self.reflectionBtn)

        self.rotatinggridLayoutWidget.raise_()
        
        self.btmAxisLabelTxt.setText("Bottom Axis")
        self.crtStepLabelTxt.setText("Current Step")
        self.topAxisLabelTxt.setText("Top Axis")
        self.statsLabelTxt.setText("Status")
        self.crtAngleLabelTxt.setText("Current Angle (°)")
        self.OperationMdLabelTxt.setText("Operation Modes")
        
        self.InitCheckBtn.setText("InitCheck")
        self.freeMoveBtn.setText("Free Move")
        self.reflectionBtn.setText("Reflection")
        
        self.InitCheckBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.freeMoveBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.reflectionBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        font.setBold(False)
        font.setPointSize(11)
        
        self.InitCheckBtn.setFont(font)                self.freeMoveBtn.setFont(font)
        self.reflectionBtn.setFont(font) 
        
        self.connectRStageButton = QtWidgets.QPushButton(self.centralWidget)
        self.connectRStageButton.setGeometry(QtCore.QRect(20, 0, 410, 60))            
        
        self.palette = self.formPalette()
        self.connectRStageButton.setPalette(self.palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.connectRStageButton.setFont(font)
        self.connectRStageButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.connectRStageButton.setObjectName("cnectButton")
        
        self.cnectSampleBtn = QtWidgets.QPushButton(self.centralWidget)
        self.cnectSampleBtn.setGeometry(QtCore.QRect(30, 455, 410, 40))            
        
        self.palette = self.formPalette()
        self.cnectSampleBtn.setPalette(self.palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cnectSampleBtn.setFont(font)
        self.cnectSampleBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cnectSampleBtn.setObjectName("cnectButton")   
        
        self.cnectSampleBtn.setText('Connect to Sample Stage')
        
        self.connectRStageButton.setText('Connect to Rotating Stage')

        MainWindow.setWindowTitle("WLR")
        
    # Extreme Laser
       
        self.cnectLaserStatusButton = QtWidgets.QLabel(self.centralWidget)
        self.cnectLaserStatusButton.setGeometry(QtCore.QRect(20, 605, 55, 55))
        self.cnectLaserStatusButton.setText("")
        self.cnectLaserStatusButton.setPixmap(QtGui.QPixmap(":/RedButton.png"))
        self.cnectLaserStatusButton.setScaledContents(True)
        self.cnectLaserStatusButton.setObjectName("cnectStatusButton") 
        
        self.LaserPowerButton = QtWidgets.QPushButton(self.centralWidget)
        self.LaserPowerButton.setGeometry(QtCore.QRect(500, 615, 40, 40))
        self.LaserPowerButton.setStyleSheet("border-color: rgb(142, 231, 255);background-color: rgb(255, 255, 255);")
        self.LaserPowerButton.setObjectName("powerButton")         

        
        self.topAxisLabelTxt = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.topAxisLabelTxt.setFont(font)
        self.topAxisLabelTxt.setObjectName("label")
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        
        self.LaserFrame = QtWidgets.QFrame(self.centralWidget)
        self.LaserFrame.setGeometry(QtCore.QRect(20, 690, 540, 300))
        self.LaserFrame.setAutoFillBackground(True)
        self.LaserFrame.setStyleSheet("border-color: rgb(142, 231, 255);")
        self.LaserFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.LaserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LaserFrame.setLineWidth(2)
        self.LaserFrame.setObjectName("LaserFrame")         
        
    
        self.readingsText = QtWidgets.QLabel(self.LaserFrame)
        self.readingsText.setGeometry(QtCore.QRect(220, -20, 150, 100))        
        self.readingsText.setFont(font)
        self.readingsText.setObjectName("parametersText") 
        
        self.promptText = QtWidgets.QLabel(self.LaserFrame)
        self.promptText.setGeometry(QtCore.QRect(380, -20, 150, 100))        
        self.promptText.setFont(font)
        self.promptText.setObjectName("promptText")     
        
        self.lcdWavelength = QtWidgets.QLCDNumber(self.LaserFrame)
        self.lcdWavelength.setStyleSheet("background-color: rgb(226, 239, 255);")        
        self.lcdWavelength.setObjectName('lcdWavelength')
        self.lcdWavelength.setGeometry(QtCore.QRect(225, 75, 100, 40))
        
        self.lcdPower = QtWidgets.QLCDNumber(self.LaserFrame)
        self.lcdPower.setStyleSheet("background-color: rgb(226, 239, 255);")        
        self.lcdPower.setObjectName('lcdPower')
        self.lcdPower.setGeometry(QtCore.QRect(225, 120, 100, 40))
        
        self.lcdFrequency = QtWidgets.QLCDNumber(self.LaserFrame)
        self.lcdFrequency.setStyleSheet("background-color: rgb(226, 239, 255);")        
        self.lcdFrequency.setObjectName('lcdFrequency')
        self.lcdFrequency.setGeometry(QtCore.QRect(225, 165, 100, 40))        
               
        self.wavelengthPrompt = QtWidgets.QTextEdit(self.LaserFrame)
        self.wavelengthPrompt.setObjectName("wavelengthPrompt")
        self.wavelengthPrompt.setGeometry(QtCore.QRect(380, 75, 110, 35))
        self.wavelengthPrompt.setFont(font)
        self.wavelengthPrompt.setText('400')        
        
        self.powerPrompt = QtWidgets.QTextEdit(self.LaserFrame)
        self.powerPrompt.setObjectName("powerPrompt")
        self.powerPrompt.setGeometry(QtCore.QRect(380, 120, 110, 35))
        self.powerPrompt.setFont(font)
        self.powerPrompt.setText('6')
    
        self.frequencyPrompt = QtWidgets.QTextEdit(self.LaserFrame)
        self.frequencyPrompt.setObjectName("frequencyPrompt")
        self.frequencyPrompt.setGeometry(QtCore.QRect(380, 165, 110, 35))
        self.frequencyPrompt.setFont(font)
        self.frequencyPrompt.setText('1')        
             
        self.wavelengthText = QtWidgets.QLabel(self.LaserFrame)
        self.wavelengthText.setFont(font)
        self.wavelengthText.setObjectName("wavelengthText")
        self.wavelengthText.setGeometry(QtCore.QRect(20, 80, 170, 40))
        
        self.powerText = QtWidgets.QLabel(self.LaserFrame)
        self.powerText.setFont(font)
        self.powerText.setObjectName("powerText")
        self.powerText.setGeometry(QtCore.QRect(20, 125, 140, 40))
        
        self.frequencyText = QtWidgets.QLabel(self.LaserFrame)
        self.frequencyText.setFont(font)
        self.frequencyText.setObjectName("frequencyText")
        self.frequencyText.setGeometry(QtCore.QRect(20, 170, 170, 40)) 
        
        self.cnectLaserButton = QtWidgets.QPushButton(self.centralWidget)
        self.cnectLaserButton.setGeometry(QtCore.QRect(120, 610, 320, 60))
        self.cnectLaserButton.setObjectName("cnectButton")
        self.cnectLaserButton.setText("Connect To Laser")
        self.cnectLaserButton.setPalette(self.palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cnectLaserButton.setFont(font)
        self.cnectLaserButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.LaserApplyButton = QtWidgets.QPushButton(self.LaserFrame)
        self.LaserApplyButton.setGeometry(QtCore.QRect(140, 230, 280, 50))
        self.LaserApplyButton.setStyleSheet("background-color: rgb(255, 255, 255);")        
        self.LaserApplyButton.setObjectName("applyButton")
        self.LaserApplyButton.setText("Apply Changes")
        fontapplyButton = QtGui.QFont()
        fontapplyButton.setFamily("Verdana")
        fontapplyButton.setPointSize(12)
        fontapplyButton.setItalic(False)
        fontapplyButton.setBold(False)
        fontapplyButton.setWeight(75)
        self.LaserApplyButton.setFont(fontapplyButton)          
    
        self.readingsText.setText("Readouts:")
        self.promptText.setText("Prompts:")
        self.wavelengthText.setText("Wavelength (nm)")
        self.powerText.setText("Power (%)")
        self.frequencyText.setText("Frequency (MHz)")
        
    # Spectrometer
    
        self.cnectSpectroButton = QtWidgets.QPushButton(self.centralWidget)
        self.cnectSpectroButton.setGeometry(QtCore.QRect(580, 0, 400, 60))
        self.cnectSpectroButton.setObjectName("cnectSpectroButton")
        self.cnectSpectroButton.setText("Connect To Spectrometer/CCD")
        self.cnectSpectroButton.setPalette(self.palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cnectSpectroButton.setFont(font)
        self.cnectSpectroButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.spectroButton = QtWidgets.QLabel(self.centralWidget)
        self.spectroButton.setMaximumSize(QtCore.QSize(60, 60))
        self.spectroButton.setGeometry(QtCore.QRect(1010, 0, 60,60))
        self.spectroButton.setText("")
        self.spectroButton.setPixmap(QtGui.QPixmap(":/RedButton.png"))
        self.spectroButton.setScaledContents(True)
        self.spectroButton.setObjectName("spectroButton")
        
    # Measurement Settings
   
        self.measButton = QtWidgets.QPushButton(self.centralWidget)
        self.measButton.setGeometry(QtCore.QRect(580, 425, 500, 65))
        self.measButton.setObjectName("Start Acquisition")
        self.measButton.setText("Start Acquisition")
        self.measButton.setPalette(self.palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.measButton.setFont(font)
        self.measButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.measFrame = QtWidgets.QFrame(self.centralWidget)
        self.measFrame.setGeometry(QtCore.QRect(580, 70, 500, 340))
        self.measFrame.setAutoFillBackground(True)
        self.measFrame.setStyleSheet("border-color: rgb(142, 231, 255);")
        self.measFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.measFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.measFrame.setLineWidth(2)
        self.measFrame.setObjectName("measurementFrame")  
        
        self.measurementLabel = QtWidgets.QLabel(self.measFrame)
        self.measurementLabel.setGeometry(QtCore.QRect(175 , -20, 170, 100))
        self.measurementLabel.setFont(font)
        self.measurementLabel.setText("Measurement:")
        
        self.palette = self.formPalette()
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        
        self.label = QtWidgets.QLabel(self.measFrame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)             
        
        safePosition = 10
        maxPosition = 70
        
        zeropositionPhi = 0 
        maxpositionPhi = 90
        
        self.startThetaPrompt = QtWidgets.QTextEdit(self.measFrame)
        self.startThetaPrompt.setObjectName("startPrompt")
        self.startThetaPrompt.setGeometry(QtCore.QRect(190, 80, 40, 30))
        self.startThetaPrompt.setFont(font)
        self.startThetaPrompt.setText(str(safePosition))
        
        self.endThetaPrompt = QtWidgets.QTextEdit(self.measFrame)
        self.endThetaPrompt.setObjectName("endPrompt")
        self.endThetaPrompt.setGeometry(QtCore.QRect(190, 130, 40, 30))
        self.endThetaPrompt.setFont(font)
        self.endThetaPrompt.setText(str(maxPosition))
        
        self.stepTPrompt = QtWidgets.QTextEdit(self.measFrame)
        self.stepTPrompt.setObjectName("stepPrompt")
        self.stepTPrompt.setFont(font)
        self.stepTPrompt.setGeometry(QtCore.QRect(180, 205, 40, 30))
        self.stepTPrompt.setText(str(10))         
        
        self.stepPPrompt = QtWidgets.QTextEdit(self.measFrame)
        self.stepPPrompt.setObjectName("stepPrompt")
        self.stepPPrompt.setFont(font)
        self.stepPPrompt.setGeometry(QtCore.QRect(180, 265, 40, 30))
        self.stepPPrompt.setText(str(10))          
        
        self.startThetaAngleText = QtWidgets.QLabel(self.measFrame)
        self.startThetaAngleText.setFont(font)
        self.startThetaAngleText.setObjectName("startTAngleText")
        self.startThetaAngleText.setGeometry(QtCore.QRect(15, 75, 180, 40))
        
        self.lastThetaAngleText = QtWidgets.QLabel(self.measFrame)
        self.lastThetaAngleText.setFont(font)
        self.lastThetaAngleText.setObjectName("lastTAngleText")
        self.lastThetaAngleText.setGeometry(QtCore.QRect(15, 130, 180, 40))
        
        self.startPhiAngleText = QtWidgets.QLabel(self.measFrame)
        self.startPhiAngleText.setFont(font)
        self.startPhiAngleText.setObjectName("startPAngleText")
        self.startPhiAngleText.setGeometry(QtCore.QRect(250, 75, 180, 40))
        
        self.lastPhiAngleText = QtWidgets.QLabel(self.measFrame)
        self.lastPhiAngleText.setFont(font)
        self.lastPhiAngleText.setObjectName("lastTAngleText")
        self.lastPhiAngleText.setGeometry(QtCore.QRect(250, 130, 180, 40))   
        
        self.startPhiPrompt = QtWidgets.QTextEdit(self.measFrame)
        self.startPhiPrompt.setObjectName("startPrompt")
        self.startPhiPrompt.setGeometry(QtCore.QRect(420, 80, 50, 30))
        self.startPhiPrompt.setFont(font)
        self.startPhiPrompt.setText(str(zeropositionPhi))
        
        self.endPhiPrompt = QtWidgets.QTextEdit(self.measFrame)
        self.endPhiPrompt.setObjectName("endPrompt")
        self.endPhiPrompt.setGeometry(QtCore.QRect(420, 130, 50, 30))
        self.endPhiPrompt.setFont(font)
        self.endPhiPrompt.setText(str(maxpositionPhi))    
        
        self.stepPText = QtWidgets.QLabel(self.measFrame)
        self.stepPText.setFont(font)
        self.stepPText.setObjectName("stepText")
        self.stepPText.setGeometry(QtCore.QRect(60, 260, 140, 40)) 
        
        self.ThetaOnlyText = QtWidgets.QLabel(self.measFrame)
        self.ThetaOnlyText.setFont(font)
        self.ThetaOnlyText.setGeometry(QtCore.QRect(270,200,140,40))
        
        self.ThetaOnlyCheck = QtWidgets.QCheckBox(self.measFrame)
        self.ThetaOnlyCheck.setGeometry(QtCore.QRect(400,200,40,40))
        
        self.stepThText = QtWidgets.QLabel(self.measFrame)
        self.stepThText.setFont(font)
        self.stepThText.setObjectName("stepText")
        self.stepThText.setGeometry(QtCore.QRect(60, 200, 140, 40))
        
        self.SampleOrientation = QtWidgets.QLabel(self.centralWidget)
        self.SampleOrientation.setFont(font)
        self.SampleOrientation.setText('Sample Orientation (Phi):')
        self.SampleOrientation.setGeometry(QtCore.QRect(40,475,300,100))
        
        self.SampleOrientationUpdtBtn = QtWidgets.QPushButton(self.centralWidget)
        self.SampleOrientationUpdtBtn.setFont(font)
        self.SampleOrientationUpdtBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SampleOrientationUpdtBtn.setText('Update Position')
        self.SampleOrientationUpdtBtn.setGeometry(QtCore.QRect(40,550,230,35))        
        
        self.SampleOrientationLCD = QtWidgets.QLCDNumber(self.centralWidget)
        self.SampleOrientationLCD.setStyleSheet("background-color: rgb(226, 239, 255);")
        self.SampleOrientationLCD.display(0)
        self.SampleOrientationLCD.setGeometry(QtCore.QRect(300,525,50,50))
        
        self.SampleOrientationGoTo = QtWidgets.QPushButton(self.centralWidget)
        self.SampleOrientationGoTo.setFont(font)
        self.SampleOrientationGoTo.setPalette(self.palette)
        self.SampleOrientationGoTo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SampleOrientationGoTo.setText('Go To')
        self.SampleOrientationGoTo.setGeometry(QtCore.QRect(370,525,100,50)) 
        
        self.SampleOrientationGoToPrompt = QtWidgets.QTextEdit(self.centralWidget)
        self.SampleOrientationGoToPrompt.setFont(font)
        self.SampleOrientationGoToPrompt.setText('0')
        self.SampleOrientationGoToPrompt.setGeometry(QtCore.QRect(500,530,50,40))        
        
        self.ThetaOnlyText.setText('Only Theta')
        self.startThetaAngleText.setText("Start T Angle (°)")
        self.lastThetaAngleText.setText("Last T Angle (°)")
        self.startPhiAngleText.setText("Start P Angle (°)")
        self.lastPhiAngleText.setText("Last P Angle (°)")         
        self.stepThText.setText("Step T (°)")
        self.stepPText.setText("Step P (°)")
        
        MainWindow.setCentralWidget(self.centralWidget)                
        
    def formPalette(self):
            
        palette = QtGui.QPalette()     
            
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        
        return palette
                        
        
if __name__ == "__main__":
    
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NpGUI = QtWidgets.QMainWindow()
    mainGUI(NpGUI)
    NpGUI.show()
    sys.exit(app.exec_())
    
# The code below has been generated from reading ui file 'UI_RsGUI.ui'

